#!/usr/bin/env node
"use strict";
/**
 * Generate deterministic catalog routers (category indexes and READMEs).
 *
 * Category folders are generated for groups with 6 or more records; smaller
 * groups stay flat and are listed only in the top-level documents index.
 * Record `path` fields are computed relative to each generated index's own
 * directory, so they stay correct whether records still live in `types/` or
 * have moved into `documents/<group>/`.
 */

const fs = require("fs");
const path = require("path");
const { fail } = require("../common/_util.js");
const queryCatalog = require("../catalog/query_catalog.js");

const SKILL_ROOT = path.resolve(__dirname, "..", "..");
const CATALOG_DIR = path.join(SKILL_ROOT, ".metadata", "catalog");
const DOCUMENTS_DIR = path.join(CATALOG_DIR, "documents");
const CATEGORY_FOLDER_THRESHOLD = 6;
// Canonical form (always .py) so Python- and Node-generated output is
// byte-identical regardless of which runtime last wrote it.
const GENERATED_MD_MARKER =
  "<!-- Generated by scripts/generate_indexes.py from " +
  ".metadata/catalog/index.json. Do not edit. -->";

function dumpJsonLf(value) {
  return JSON.stringify(value, null, 2) + "\n";
}

/** POSIX-separated path from `fromDir` to a record given relative to CATALOG_DIR. */
function relativeRecordPath(record, fromDir) {
  return path.relative(fromDir, path.join(CATALOG_DIR, record)).split(path.sep).join("/");
}

function groupedRecords(index) {
  const groups = {};
  for (const group of index.groups) groups[group] = [];
  for (const row of index.document_types) {
    const detail = queryCatalog.loadType(row.id);
    const group = detail.group;
    const record = row.record || `types/${row.id}.json`;
    if (!groups[group]) groups[group] = [];
    groups[group].push([detail.write_order || 0, detail.id, detail, record]);
  }
  for (const group of Object.keys(groups)) {
    groups[group].sort((a, b) => (a[0] - b[0]) || a[1].localeCompare(b[1]));
  }
  return groups;
}

function isFolderGroup(records) {
  return records.length >= CATEGORY_FOLDER_THRESHOLD;
}

function categoryIndexPayload(group, records) {
  const categoryDir = path.join(DOCUMENTS_DIR, group);
  return {
    $schema: "../category-index-schema.json",
    version: queryCatalog.CATALOG_VERSION,
    category: group,
    purpose: queryCatalog.GROUP_SUMMARIES[group] || `${group} document definitions`,
    source: "../index.json",
    records: records.map(([, docId, detail, record]) => ({
      id: docId,
      path: relativeRecordPath(record, categoryDir),
      summary: detail.summary || "",
    })),
  };
}

function categoryReadmeText(group, records) {
  const purpose = queryCatalog.GROUP_SUMMARIES[group] || `${group} document definitions`;
  const entries = records.map(
    ([, docId, detail]) => `- \`${docId}\` — ${detail.summary || ""} → [index.json](index.json)`,
  );
  const blocks = [
    GENERATED_MD_MARKER,
    `# ${group}`,
    purpose,
    "## Contents\n\n" + entries.join("\n"),
  ];
  return blocks.join("\n\n") + "\n";
}

function documentsIndexPayload(index, groups) {
  const entries = index.groups.map((group) => {
    const records = groups[group] || [];
    if (isFolderGroup(records)) {
      return { id: group, kind: "folder", index: `${group}/index.json`, count: records.length };
    }
    return {
      id: group,
      kind: "flat",
      records: records.map(([, docId, detail, record]) => ({
        id: docId,
        path: relativeRecordPath(record, DOCUMENTS_DIR),
        summary: detail.summary || "",
      })),
      count: records.length,
    };
  });
  return {
    version: queryCatalog.CATALOG_VERSION,
    source: "../index.json",
    groups: entries,
  };
}

function documentsReadmeText(index, groups) {
  const entries = index.groups.map((group) => {
    const records = groups[group] || [];
    const purpose = queryCatalog.GROUP_SUMMARIES[group] || `${group} document definitions`;
    if (isFolderGroup(records)) {
      return `- [${group}/](${group}/index.json) — ${purpose} (${records.length} documents)`;
    }
    return `- ${group} — ${purpose} (${records.length} documents, flat)`;
  });
  const blocks = [
    GENERATED_MD_MARKER,
    "# Catalog documents",
    "One folder per large group; small groups stay flat.",
    "## Contents\n\n" + entries.join("\n"),
  ];
  return blocks.join("\n\n") + "\n";
}

function catalogReadmeText(index) {
  const blocks = [
    GENERATED_MD_MARKER,
    "# Catalog",
    "Machine-readable document catalog. Query it via `scripts/query_catalog.py`" +
      " / `.js` rather than reading these files directly.",
    "## Load this when\n\n" +
      "- Choosing among documents in a group → " +
      "[documents/README.md](documents/README.md)\n" +
      "- Resolving one document id → `query_catalog --route <id>`",
    "## Contents\n\n" +
      "- [index.json](index.json) — root catalog: tiers, groups, capabilities, " +
      "profile paths, and every document's `record` path.\n" +
      "- [documents/](documents/README.md) — per-group generated routers.\n" +
      "- [profiles/](profiles/) — shape/platform/framework/concern/audience " +
      "definitions.",
    "## Boundaries\n\n" +
      `${index.document_types.length} document records across ` +
      `${index.groups.length} groups. Category indexes are generated views; ` +
      "`index.json` and each record file remain authoritative.",
  ];
  return blocks.join("\n\n") + "\n";
}

function targets(index) {
  const groups = groupedRecords(index);
  const out = new Map();
  out.set(path.join(DOCUMENTS_DIR, "index.json"), dumpJsonLf(documentsIndexPayload(index, groups)));
  out.set(path.join(DOCUMENTS_DIR, "README.md"), documentsReadmeText(index, groups));
  out.set(path.join(CATALOG_DIR, "README.md"), catalogReadmeText(index, groups));
  for (const [group, records] of Object.entries(groups)) {
    if (!isFolderGroup(records)) continue;
    out.set(
      path.join(DOCUMENTS_DIR, group, "index.json"),
      dumpJsonLf(categoryIndexPayload(group, records)),
    );
    out.set(path.join(DOCUMENTS_DIR, group, "README.md"), categoryReadmeText(group, records));
  }
  return out;
}

/** Return generated paths whose on-disk content disagrees with the catalog. No writes. */
function staleTargets() {
  const index = queryCatalog.loadIndex();
  const expected = targets(index);
  const stale = [];
  for (const [target, content] of expected) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (current !== content) stale.push(target);
  }
  return stale;
}

/** Write every stale generated path and return the ones actually written. */
function writeTargets() {
  const index = queryCatalog.loadIndex();
  const expected = targets(index);
  const changed = [];
  for (const [target, content] of expected) {
    const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : null;
    if (current === content) continue;
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, content, "utf8");
    changed.push(target);
  }
  return changed;
}

function run({ write }) {
  if (write) {
    const changed = writeTargets();
    for (const target of changed) console.log(`WROTE  ${path.relative(SKILL_ROOT, target)}`);
    if (!changed.length) console.log("no changes");
    return 0;
  }
  const stale = staleTargets();
  if (stale.length) {
    for (const target of stale) console.log(`STALE  ${path.relative(SKILL_ROOT, target)}`);
    console.log(`\n${stale.length} generated file(s) out of date; run with --write`);
    return 1;
  }
  console.log("generated routers are up to date");
  return 0;
}

function parseArgs(argv) {
  const args = {};
  for (const arg of argv) {
    if (arg === "--write") args.write = true;
    else if (arg === "--check") args.check = true;
    else throw new Error(`unknown flag: ${arg}`);
  }
  return args;
}

function main(argv = process.argv.slice(2)) {
  let args;
  try {
    args = parseArgs(argv);
  } catch (error) {
    return fail(error.message, 2);
  }
  if (Boolean(args.write) === Boolean(args.check)) {
    return fail("specify exactly one of --write, --check", 2);
  }
  try {
    return run({ write: Boolean(args.write) });
  } catch (error) {
    return fail(error.message, 2);
  }
}

module.exports = { main, staleTargets, writeTargets };

if (require.main === module) {
  process.exitCode = main();
}
