import { source } from '@/lib/source';
import { DocsLayout } from 'fumadocs-ui/layouts/docs';
import { baseOptions } from '@/lib/layout.shared';
import type { ReactNode } from 'react';

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <DocsLayout tree={source.getPageTree()} {...baseOptions()}>
      <div className="flex min-h-screen flex-col">
        <div className="flex-1">{children}</div>
        <footer className="mt-12 flex flex-wrap items-center gap-x-1 gap-y-0.5 border-t border-fd-border py-3 text-xs text-fd-muted-foreground">
          <span>Documentation generated by</span>
          <a
            href="https://github.com/jonaskahn/docforge"
            target="_blank"
            rel="noreferrer"
            className="text-fd-foreground hover:underline"
          >
            Docforge
          </a>
          <span aria-hidden="true">·</span>
          <span>UI by</span>
          <a
            href="https://www.fumadocs.dev/"
            target="_blank"
            rel="noreferrer"
            className="text-fd-foreground hover:underline"
          >
            Fumadocs
          </a>
        </footer>
      </div>
    </DocsLayout>
  );
}
