#!/usr/bin/env python3
"""Generate deterministic catalog routers (category indexes and READMEs).

Category folders are generated for groups with 6 or more records; smaller
groups stay flat and are listed only in the top-level documents index. Record
`path` fields are computed relative to each generated index's own directory,
so they stay correct whether records still live in `types/` or have moved
into `documents/<group>/`.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from runtime.catalog import query_catalog
from runtime.common._util import fail

SKILL_ROOT = Path(__file__).resolve().parent.parent.parent
CATALOG_DIR = SKILL_ROOT / ".metadata" / "catalog"
DOCUMENTS_DIR = CATALOG_DIR / "documents"
CATEGORY_FOLDER_THRESHOLD = 6
# Canonical form (always .py) so Python- and Node-generated output is
# byte-identical regardless of which runtime last wrote it.
GENERATED_MD_MARKER = (
    "<!-- Generated by runtime/cli/python/generate_indexes.py from "
    ".metadata/catalog/index.json. Do not edit. -->\n"
)


def dump_json_lf(value: object) -> str:
    import json
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def relative_record_path(record: str, from_dir: Path) -> str:
    """POSIX-separated path from `from_dir` to a record given relative to CATALOG_DIR."""
    rel = os.path.relpath(CATALOG_DIR / record, from_dir)
    return rel.replace(os.sep, "/")


def grouped_records(index: dict) -> dict[str, list[tuple[int, str, dict, str]]]:
    groups: dict[str, list[tuple[int, str, dict, str]]] = {group: [] for group in index["groups"]}
    for row in index["document_types"]:
        detail = query_catalog.load_type(row["id"])
        group = detail["group"]
        record = row.get("record", f"types/{row['id']}.json")
        groups.setdefault(group, []).append((detail.get("write_order", 0), detail["id"], detail, record))
    for group in groups:
        groups[group].sort(key=lambda item: (item[0], item[1]))
    return groups


def is_folder_group(records: list) -> bool:
    return len(records) >= CATEGORY_FOLDER_THRESHOLD


def category_index_payload(group: str, records: list[tuple[int, str, dict, str]]) -> dict:
    category_dir = DOCUMENTS_DIR / group
    return {
        "$schema": "../category-index-schema.json",
        "version": query_catalog.CATALOG_VERSION,
        "category": group,
        "purpose": query_catalog.GROUP_SUMMARIES.get(group, f"{group} document definitions"),
        "source": "../index.json",
        "records": [
            {
                "id": doc_id,
                "path": relative_record_path(record, category_dir),
                "summary": detail.get("summary", ""),
            }
            for _, doc_id, detail, record in records
        ],
    }


def category_readme_text(group: str, records: list[tuple[int, str, dict, str]]) -> str:
    purpose = query_catalog.GROUP_SUMMARIES.get(group, f"{group} document definitions")
    entries = [
        f"- `{doc_id}` — {detail.get('summary', '')} → [index.json](index.json)"
        for _, doc_id, detail, _record in records
    ]
    blocks = [
        GENERATED_MD_MARKER.rstrip("\n"),
        f"# {group}",
        purpose,
        "## Contents\n\n" + "\n".join(entries),
    ]
    return "\n\n".join(blocks) + "\n"


def documents_index_payload(index: dict, groups: dict[str, list]) -> dict:
    entries = []
    for group in index["groups"]:
        records = groups.get(group, [])
        if is_folder_group(records):
            entries.append({"id": group, "kind": "folder", "index": f"{group}/index.json", "count": len(records)})
        else:
            entries.append({
                "id": group,
                "kind": "flat",
                "records": [
                    {
                        "id": doc_id,
                        "path": relative_record_path(record, DOCUMENTS_DIR),
                        "summary": detail.get("summary", ""),
                    }
                    for _, doc_id, detail, record in records
                ],
                "count": len(records),
            })
    return {
        "version": query_catalog.CATALOG_VERSION,
        "source": "../index.json",
        "groups": entries,
    }


def documents_readme_text(index: dict, groups: dict[str, list]) -> str:
    entries = []
    for group in index["groups"]:
        records = groups.get(group, [])
        purpose = query_catalog.GROUP_SUMMARIES.get(group, f"{group} document definitions")
        if is_folder_group(records):
            entries.append(f"- [{group}/]({group}/index.json) — {purpose} ({len(records)} documents)")
        else:
            entries.append(f"- {group} — {purpose} ({len(records)} documents, flat)")
    blocks = [
        GENERATED_MD_MARKER.rstrip("\n"),
        "# Catalog documents",
        "One folder per large group; small groups stay flat.",
        "## Contents\n\n" + "\n".join(entries),
    ]
    return "\n\n".join(blocks) + "\n"


def catalog_readme_text(index: dict, groups: dict[str, list]) -> str:
    blocks = [
        GENERATED_MD_MARKER.rstrip("\n"),
        "# Catalog",
        "Machine-readable document catalog. Query it via `runtime/cli/python/query_catalog.py`"
        " / `.js` rather than reading these files directly.",
        "## Load this when\n\n"
        "- Choosing among documents in a group → "
        "[documents/README.md](documents/README.md)\n"
        "- Resolving one document id → `query_catalog --route <id>`",
        "## Contents\n\n"
        "- [index.json](index.json) — root catalog: tiers, groups, capabilities, "
        "profile paths, and every document's `record` path.\n"
        "- [documents/](documents/README.md) — per-group generated routers.\n"
        "- [profiles/](profiles/) — shape/platform/framework/concern/audience "
        "definitions.",
        "## Boundaries\n\n"
        f"{len(index['document_types'])} document records across "
        f"{len(index['groups'])} groups. Category indexes are generated views; "
        "`index.json` and each record file remain authoritative.",
    ]
    return "\n\n".join(blocks) + "\n"


def targets(index: dict) -> dict[Path, str]:
    groups = grouped_records(index)
    out: dict[Path, str] = {
        DOCUMENTS_DIR / "index.json": dump_json_lf(documents_index_payload(index, groups)),
        DOCUMENTS_DIR / "README.md": documents_readme_text(index, groups),
        CATALOG_DIR / "README.md": catalog_readme_text(index, groups),
    }
    for group, records in groups.items():
        if not is_folder_group(records):
            continue
        out[DOCUMENTS_DIR / group / "index.json"] = dump_json_lf(category_index_payload(group, records))
        out[DOCUMENTS_DIR / group / "README.md"] = category_readme_text(group, records)
    return out


def stale_targets() -> list[Path]:
    """Return generated paths whose on-disk content disagrees with the catalog. No writes."""
    index = query_catalog.load_index()
    expected = targets(index)
    stale: list[Path] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            stale.append(path)
    return stale


def write_targets() -> list[Path]:
    """Write every stale generated path and return the ones actually written."""
    index = query_catalog.load_index()
    expected = targets(index)
    changed: list[Path] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        changed.append(path)
    return changed


def run(*, write: bool) -> int:
    if write:
        changed = write_targets()
        for path in changed:
            print(f"WROTE  {path.relative_to(SKILL_ROOT)}")
        if not changed:
            print("no changes")
        return 0
    stale = stale_targets()
    if stale:
        for path in stale:
            print(f"STALE  {path.relative_to(SKILL_ROOT)}")
        print(f"\n{len(stale)} generated file(s) out of date; run with --write")
        return 1
    print("generated routers are up to date")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.write == args.check:
        return fail("specify exactly one of --write, --check", 2)
    try:
        return run(write=args.write)
    except ValueError as exc:
        return fail(str(exc), 2)


if __name__ == "__main__":
    raise SystemExit(main())
