#!/usr/bin/env python3
"""Generate deterministic catalog routers (category indexes and READMEs).

Category folders are generated for groups with 6 or more records; smaller
groups stay flat and are listed only in the top-level documents index. Record
`path` fields are computed relative to each generated index's own directory,
so they stay correct whether records still live in `types/` or have moved
into `documents/<group>/`.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

from runtime.catalog import query_catalog
from runtime.common._util import fail

SKILL_ROOT = Path(__file__).resolve().parent.parent.parent
CATALOG_DIR = SKILL_ROOT / ".metadata" / "catalog"
DOCUMENTS_DIR = CATALOG_DIR / "documents"
CATEGORY_FOLDER_THRESHOLD = 6
# Canonical form (always .py) so Python- and Node-generated output is
# byte-identical regardless of which runtime last wrote it.
GENERATED_MD_MARKER = (
    "<!-- Generated by runtime/cli/python/generate_indexes.py from "
    ".metadata/catalog/index.json. Do not edit. -->\n"
)
GROUP_DETAILS = {
    "root": "Repository entrypoints explain what the project is, how to start, and how its documentation system is installed and invoked.",
    "product": "Product documents describe audience value, supported journeys, requirements, releases, and the policy behind externally visible behavior.",
    "architecture": "Architecture documents explain stable system boundaries, component responsibilities, data movement, dependency direction, and decisions that shape the system.",
    "flows": "Flow documents trace evidence-backed end-to-end behavior. They complement architecture by showing ordered work across entry points, components, and failure paths.",
    "engineering": "Engineering documents establish local development expectations: setup, conventions, tests, quality checks, publishing, and sustainable maintenance practices.",
    "operations": "Operations documents cover deployment, observability, recovery, and the operational boundaries that keep production behavior understandable and safe.",
    "reference": "Reference documents are lookup-oriented contracts for APIs, configuration, compatibility, commands, errors, and vocabulary rather than narrative explanations.",
    "security": "Security documents identify assets, trust zones, applicable threats, safeguards, and the evidence needed to review residual uncertainty safely.",
    "contributing": "Contribution documents route collaborators to ownership, contribution rules, and the supporting process needed to make changes safely.",
    "records": "Decision records preserve why durable architectural choices were made. Their router indexes status and links; each individual record owns its rationale.",
    "portfolio": "Portfolio documents align multiple repositories for diligence, ownership, system context, operations, and cross-repository decision making.",
    "agent-context": "Agent-context documents provide compact, verified operating context for coding agents while linking to the human-facing owners of detailed facts.",
}


def dump_json_lf(value: object) -> str:
    import json
    return json.dumps(value, indent=2, ensure_ascii=False) + "\n"


def relative_record_path(record: str, from_dir: Path) -> str:
    """POSIX-separated path from `from_dir` to a record given relative to CATALOG_DIR."""
    rel = os.path.relpath(CATALOG_DIR / record, from_dir)
    return rel.replace(os.sep, "/")


def grouped_records(index: dict) -> dict[str, list[tuple[int, str, dict, str]]]:
    groups: dict[str, list[tuple[int, str, dict, str]]] = {group: [] for group in index["groups"]}
    for row in index["document_types"]:
        detail = query_catalog.load_type(row["id"])
        group = detail["group"]
        record = row.get("record", f"types/{row['id']}.json")
        groups.setdefault(group, []).append((detail.get("write_order", 0), detail["id"], detail, record))
    for group in groups:
        groups[group].sort(key=lambda item: (item[0], item[1]))
    return groups


def is_folder_group(records: list) -> bool:
    return len(records) >= CATEGORY_FOLDER_THRESHOLD


def category_index_payload(group: str, records: list[tuple[int, str, dict, str]]) -> dict:
    category_dir = DOCUMENTS_DIR / group
    return {
        "$schema": "../../category-index-schema.json",
        "version": query_catalog.CATALOG_VERSION,
        "category": group,
        "purpose": query_catalog.GROUP_SUMMARIES.get(group, f"{group} document definitions"),
        "source": "../../index.json",
        "records": [
            {
                "id": doc_id,
                "path": relative_record_path(record, category_dir),
                "summary": detail.get("summary", ""),
            }
            for _, doc_id, detail, record in records
        ],
    }


def category_readme_text(group: str, records: list[tuple[int, str, dict, str]]) -> str:
    purpose = query_catalog.GROUP_SUMMARIES.get(group, f"{group} document definitions")
    entries = [
        f"- `{doc_id}` — {detail.get('summary', '')} → [index.json](index.json)"
        for _, doc_id, detail, _record in records
    ]
    blocks = [
        GENERATED_MD_MARKER.rstrip("\n"),
        f"# {group}",
        purpose,
        "## Purpose\n\n" + GROUP_DETAILS.get(group, purpose),
        "## How to use this index\n\n"
        "Use the entries below to locate a document definition, then resolve it with "
        "`query_catalog --route <id>` before writing. The route provides the contract, "
        "instruction, template, prerequisites, reader depth, and any model-native rigor. "
        "This generated index is navigation only; the record and linked content artifacts "
        "remain authoritative.",
        "## Contents\n\n" + "\n".join(entries),
        "## Boundaries\n\n"
        "Entries are ordered by catalog write order. Selection rules decide whether a "
        "document belongs in a project; this index does not imply that every entry is "
        "selected for every repository or tier.",
    ]
    return "\n\n".join(blocks) + "\n"


def documents_index_payload(index: dict, groups: dict[str, list]) -> dict:
    entries = []
    for group in index["groups"]:
        records = groups.get(group, [])
        if is_folder_group(records):
            entries.append({"id": group, "kind": "folder", "index": f"{group}/index.json", "count": len(records)})
        else:
            entries.append({
                "id": group,
                "kind": "flat",
                "records": [
                    {
                        "id": doc_id,
                        "path": relative_record_path(record, DOCUMENTS_DIR),
                        "summary": detail.get("summary", ""),
                    }
                    for _, doc_id, detail, record in records
                ],
                "count": len(records),
            })
    return {
        "version": query_catalog.CATALOG_VERSION,
        "source": "../index.json",
        "groups": entries,
    }


def documents_readme_text(index: dict, groups: dict[str, list]) -> str:
    entries = []
    for group in index["groups"]:
        records = groups.get(group, [])
        purpose = query_catalog.GROUP_SUMMARIES.get(group, f"{group} document definitions")
        if is_folder_group(records):
            entries.append(f"- [{group}/]({group}/index.json) — {purpose} ({len(records)} documents)")
        else:
            entries.append(f"- {group} — {purpose} ({len(records)} documents, flat)")
    blocks = [
        GENERATED_MD_MARKER.rstrip("\n"),
        "# Catalog documents",
        "This generated index is the catalog's directory-level navigation layer. It groups "
        "document definitions without duplicating their contracts or selection policy.",
        "## How to use it\n\n"
        "Choose the subject area below, then use its generated group index to identify a "
        "document. Resolve the selected document through `query_catalog --route <id>` "
        "before reading a contract or starting work. Small groups remain flat because a "
        "separate directory adds navigation cost without helping discovery.",
        "## Contents\n\n" + "\n".join(entries),
        "## Boundaries\n\n"
        "This page is regenerated from the catalog. It is not a writing plan and does not "
        "override profile selection, tier requirements, fact ownership, or document status.",
    ]
    return "\n\n".join(blocks) + "\n"


def catalog_readme_text(index: dict, groups: dict[str, list]) -> str:
    blocks = [
        GENERATED_MD_MARKER.rstrip("\n"),
        "# Catalog",
        "The catalog is Docforge's machine-readable map of document types, selection rules, "
        "writing order, ownership boundaries, and generated-content inputs. Query it via "
        "`runtime/cli/python/query_catalog.py` or the equivalent Node launcher rather than "
        "treating generated indexes as source data.",
        "## Start here\n\n"
        "- Browse a subject area → [documents/INDEX.md](documents/INDEX.md)\n"
        "- Resolve one document and its writing inputs → `query_catalog --route <id>`\n"
        "- Check which documents a profile selects → `query_catalog --applicable ...`\n"
        "- Validate the split catalog before changing it → `query_catalog --validate`",
        "## Structure\n\n"
        "The root index owns tiers, capability names, profile registries, and the list of "
        "document records. Each record owns its selection rule, target depth, contract, "
        "template, instruction, and audit profile. The generated routers below are readable "
        "views over those records, not duplicate configuration.",
        "## Contents\n\n"
        "- [index.json](index.json) — root catalog: tiers, groups, capabilities, "
        "profile paths, and every document's `record` path.\n"
        "- [documents/](documents/INDEX.md) — per-group generated routers.\n"
        "- [profiles/](profiles/) — shape/platform/framework/concern/audience "
        "definitions.",
        "## Boundaries\n\n"
        f"{len(index['document_types'])} document records across "
        f"{len(index['groups'])} groups. Category indexes are generated views; "
        "`index.json` and each record file remain authoritative. Regenerate these INDEX.md "
        "views with `generate_indexes --write`; never edit them directly.",
    ]
    return "\n\n".join(blocks) + "\n"


def targets(index: dict) -> dict[Path, str]:
    groups = grouped_records(index)
    out: dict[Path, str] = {
        DOCUMENTS_DIR / "index.json": dump_json_lf(documents_index_payload(index, groups)),
        DOCUMENTS_DIR / "INDEX.md": documents_readme_text(index, groups),
        CATALOG_DIR / "INDEX.md": catalog_readme_text(index, groups),
    }
    for group, records in groups.items():
        if not is_folder_group(records):
            continue
        out[DOCUMENTS_DIR / group / "index.json"] = dump_json_lf(category_index_payload(group, records))
        out[DOCUMENTS_DIR / group / "INDEX.md"] = category_readme_text(group, records)
    return out


def stale_targets() -> list[Path]:
    """Return generated paths whose on-disk content disagrees with the catalog. No writes."""
    index = query_catalog.load_index()
    expected = targets(index)
    stale: list[Path] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            stale.append(path)
    return stale


def write_targets() -> list[Path]:
    """Write every stale generated path and return the ones actually written."""
    index = query_catalog.load_index()
    expected = targets(index)
    changed: list[Path] = []
    for path, content in expected.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        changed.append(path)
    return changed


def run(*, write: bool) -> int:
    if write:
        changed = write_targets()
        for path in changed:
            print(f"WROTE  {path.relative_to(SKILL_ROOT)}")
        if not changed:
            print("no changes")
        return 0
    stale = stale_targets()
    if stale:
        for path in stale:
            print(f"STALE  {path.relative_to(SKILL_ROOT)}")
        print(f"\n{len(stale)} generated file(s) out of date; run with --write")
        return 1
    print("generated routers are up to date")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    if args.write == args.check:
        return fail("specify exactly one of --write, --check", 2)
    try:
        return run(write=args.write)
    except ValueError as exc:
        return fail(str(exc), 2)


if __name__ == "__main__":
    raise SystemExit(main())
