import { source } from '@/lib/source';
import { DocsBody, DocsPage } from 'fumadocs-ui/layouts/glass/page';
import { notFound } from 'next/navigation';
import { getMDXComponents } from '@/components/mdx';
import type { Metadata } from 'next';
import { createRelativeLink } from 'fumadocs-ui/mdx';
import { appName } from '@/lib/shared';

export default async function Page({ params }: { params: Promise<{ slug?: string[] }> }) {
  const { slug } = await params;
  const page = source.getPage(slug);
  if (!page) notFound();

  const MDX = page.data.body;

  return (
    <DocsPage toc={page.data.toc}>
      <DocsBody>
        <MDX
          components={getMDXComponents({
            // allows linking to other pages with relative file paths
            a: createRelativeLink(source, page),
          })}
        />
      </DocsBody>
      <footer className="border-t pt-4 text-sm text-fd-muted-foreground">
        <p>
          Documentation generated by{' '}
          <a
            href="https://github.com/jonaskahn/docforge"
            target="_blank"
            rel="noreferrer noopener"
            className="text-fd-foreground underline underline-offset-4"
          >
            Docforge
          </a>
          {' · '}UI by{' '}
          <a
            href="https://www.fumadocs.dev/"
            target="_blank"
            rel="noreferrer noopener"
            className="text-fd-foreground underline underline-offset-4"
          >
            Fumadocs
          </a>
          .
        </p>
      </footer>
    </DocsPage>
  );
}

export async function generateStaticParams() {
  return source.generateParams();
}

export async function generateMetadata({ params }: { params: Promise<{ slug?: string[] }> }): Promise<Metadata> {
  const { slug } = await params;
  const page = source.getPage(slug);
  if (!page) notFound();

  return {
    title: page.data.title ? `${page.data.title} | ${appName}` : appName,
    description: page.data.description,
  };
}
